# Generated by Django 5.0 on 2026-02-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_reported",
            field=models.BooleanField(default=False),
        ),
    ]
